# Generated by Django 5.0.7 on 2024-07-27 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите фамилию, имя и отчество",
                        max_length=200,
                        verbose_name="ФИО",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Введите должность",
                        max_length=100,
                        verbose_name="должность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование задачи",
                        max_length=200,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        help_text="Укажите срок выполнения задачи", verbose_name="Срок"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("planned", "Запланирована"),
                            ("in_progress", "Выполняется"),
                            ("canceled", "Отменена"),
                            ("completed", "Выполнена"),
                        ],
                        help_text="Выберите статус задачи",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Выберите исполнителя задачи",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.employee",
                        verbose_name="Исполнитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
