# Generated by Django 5.0.7 on 2024-07-29 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите исполнителя задачи",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.employee",
                verbose_name="Исполнитель",
            ),
        ),
    ]
